### ISSUE TITLE
calculation of days since last rehab

### ISSUE THREAD

**Issue by mriech** [KWB-R/dwc.wells#13]
@mrustl Could you please check the calculation of days_since_last_rehab? It looks a bit strange (see attachment).
![screenshot_pump_test_data](https://user-images.githubusercontent.com/47454653/118628210-b30b3680-b7cc-11eb-9504-b7187ea54a0c.PNG)

**Comment by mrustl** [comment]
Sorry for that @mriech. Should be closed now via https://github.com/KWB-R/dwc.wells/commit/d905ee1ce8b3c756f0a13eed2cce4f936af82a9f

You can check the table below (also solving the Qrel issue described in #14):

| well_id| action_id|key               |date       |        Qs|   Q| W_static| W_dyamic| W_dynamic|    Qs_rel|well_rehab |substitute_pump |pressure_sleeve |comment_liner |operational_start.date | days_since_operational_start| days_since_last_action| n.well_rehab| n.substitute_pump| n.pressure_sleeve| n.comment_liner| days_since_operational_start_rehab| days_since_last_rehab|
|-------:|---------:|:-----------------|:----------|---------:|---:|--------:|--------:|---------:|---------:|:----------|:---------------|:---------------|:-------------|:----------------------|----------------------------:|----------------------:|------------:|-----------------:|-----------------:|---------------:|----------------------------------:|---------------------:|
|     162|         0|operational_start |1970-12-14 | 39.000000| 150| 5.600000|     9.44|        NA| 1.0000000|NA         |NA              |NA              |NA            |1970-12-14             |                            0|                      0|            0|                 0|                 0|               0|                                  0|                     0|
|     162|         1|pump_test_2       |1994-02-13 | 38.216556| 180| 4.720000|       NA|      9.43| 0.9799117|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                         8462|                   8462|            1|                 1|                 0|               0|                               8462|                  8462|
|     162|         2|pump_test_1       |2000-04-09 | 29.329608| 210| 5.180000|       NA|     12.34| 0.7520412|NA         |NA              |NA              |NA            |1970-12-14             |                        10709|                   2247|            1|                 1|                 0|               0|                               8462|                  8462|
|     162|         2|pump_test_2       |2000-06-07 | 30.648332| 156| 6.030000|       NA|     11.12| 0.7858547|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                        10768|                     59|            2|                 2|                 0|               0|                              10768|                  2306|
|     162|         3|pump_test_1       |2005-11-27 | 20.408165|  50| 4.840000|       NA|      7.29| 0.5232863|NA         |NA              |NA              |NA            |1970-12-14             |                        12767|                   1999|            2|                 2|                 0|               0|                              10768|                  2306|
|     162|         3|pump_test_2       |2005-11-30 | 23.923449|  50| 4.840000|       NA|      6.93| 0.6134218|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                        12770|                      3|            3|                 3|                 0|               0|                              12770|                  2002|
|     162|         4|pump_test_1       |2010-06-29 | 15.444016| 120| 5.220000|       NA|     12.99| 0.3960004|NA         |NA              |NA              |NA            |1970-12-14             |                        14442|                   1672|            3|                 3|                 0|               0|                              12770|                  2002|
|     162|         4|pump_test_2       |2010-07-14 | 19.512195| 120| 6.180000|       NA|     12.33| 0.5003127|TRUE       |TRUE            |TRUE            |FALSE         |1970-12-14             |                        14457|                     15|            4|                 4|                 1|               0|                              14457|                  1687|
|     162|         5|pump_test_1       |2013-03-20 | 12.307692|  40| 5.600000|       NA|      8.85| 0.3155819|NA         |NA              |NA              |NA            |1970-12-14             |                        15437|                    980|            4|                 4|                 1|               0|                              14457|                  1687|
|     162|         5|pump_test_2       |2013-11-20 | 10.638298|  50| 6.380000|       NA|     11.08| 0.2727769|TRUE       |TRUE            |FALSE           |TRUE          |1970-12-14             |                        15682|                    245|            5|                 5|                 1|               1|                              15682|                  1225|
|     162|         6|pump_test_1       |2015-02-16 |  8.103728|  50| 6.450000|       NA|     12.62| 0.2077879|NA         |NA              |NA              |NA            |1970-12-14             |                        16135|                    453|            5|                 5|                 1|               1|                              15682|                  1225|
|     166|         0|operational_start |1994-06-01 | 45.000000| 180| 3.810000|     7.84|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-06-01             |                            0|                      0|            0|                 0|                 0|               0|                                 -9|                    -9|
|     166|         1|pump_test_2       |1994-05-23 | 48.387098| 150| 5.400000|       NA|      8.50| 1.0752689|FALSE      |TRUE            |FALSE           |FALSE         |1994-06-01             |                           -9|                     -9|            0|                 1|                 0|               0|                                 -9|                    -9|
|     166|         2|pump_test_1       |2000-06-04 | 53.571426| 180| 7.060000|       NA|     10.42| 1.1904761|NA         |NA              |NA              |NA            |1994-06-01             |                         2195|                   2204|            0|                 1|                 0|               0|                                 -9|                    -9|
|     166|         2|pump_test_2       |2000-06-27 | 41.131102| 160| 8.130000|       NA|     12.02| 0.9140245|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         2218|                     23|            1|                 2|                 0|               0|                               2218|                  2227|
|     166|         3|pump_test_1       |2005-12-12 | 31.152652| 100| 4.530000|       NA|      7.74| 0.6922812|NA         |NA              |NA              |NA            |1994-06-01             |                         4212|                   1994|            1|                 2|                 0|               0|                               2218|                  2227|
|     166|         3|pump_test_2       |2005-12-20 | 32.573288| 100| 4.180000|       NA|      7.25| 0.7238508|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         4220|                      8|            2|                 3|                 0|               0|                               4220|                  2002|
|     166|         4|pump_test_1       |2010-05-02 | 18.484287| 100| 6.310000|       NA|     11.72| 0.4107619|NA         |NA              |NA              |NA            |1994-06-01             |                         5814|                   1594|            2|                 3|                 0|               0|                               4220|                  2002|
|     166|         4|pump_test_2       |2010-05-19 | 32.258066| 100| 5.180000|       NA|      8.28| 0.7168459|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         5831|                     17|            3|                 4|                 0|               0|                               5831|                  1611|
|     166|         5|pump_test_1       |2015-04-21 | 15.682657|  85| 7.490000|       NA|     12.91| 0.3485035|NA         |NA              |NA              |NA            |1994-06-01             |                         7629|                   1798|            3|                 4|                 0|               0|                               5831|                  1611|
|     166|         5|pump_test_2       |2015-05-11 | 23.460411|  80| 6.090000|       NA|      9.50| 0.5213425|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         7649|                     20|            4|                 5|                 0|               0|                               7649|                  1818|
|     167|         0|operational_start |1994-06-01 | 25.000000| 150| 4.410000|    10.45|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-06-01             |                            0|                      0|            0|                 0|                 0|               0|                                 -9|                    -9|
|     167|         1|pump_test_2       |1994-05-23 | 23.121390|  80| 5.150000|       NA|      8.61| 0.9248556|FALSE      |TRUE            |FALSE           |FALSE         |1994-06-01             |                           -9|                     -9|            0|                 1|                 0|               0|                                 -9|                    -9|
|     167|         2|pump_test_1       |2000-06-04 | 18.552875| 100| 7.250000|       NA|     12.64| 0.7421150|NA         |NA              |NA              |NA            |1994-06-01             |                         2195|                   2204|            0|                 1|                 0|               0|                                 -9|                    -9|
|     167|         2|pump_test_2       |2000-06-27 | 20.533881| 100| 8.280000|       NA|     13.15| 0.8213553|TRUE       |FALSE           |FALSE           |FALSE         |1994-06-01             |                         2218|                     23|            1|                 1|                 0|               0|                               2218|                  2227|
|     167|         3|pump_test_1       |2005-12-07 | 11.904762|  50| 5.050000|       NA|      9.25| 0.4761905|NA         |NA              |NA              |NA            |1994-06-01             |                         4207|                   1989|            1|                 1|                 0|               0|                               2218|                  2227|
|     167|         3|pump_test_2       |2005-12-12 | 12.224940|  50| 4.780000|       NA|      8.87| 0.4889976|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         4212|                      5|            2|                 2|                 0|               0|                               4212|                  1994|
|     167|         4|pump_test_1       |2010-08-16 |  4.721436|  50| 5.070000|       NA|     15.66| 0.1888574|NA         |NA              |NA              |NA            |1994-06-01             |                         5920|                   1708|            2|                 2|                 0|               0|                               4212|                  1994|
|     167|         4|pump_test_2       |2010-09-06 |  7.173601|  50| 5.550000|       NA|     12.52| 0.2869440|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         5941|                     21|            3|                 3|                 0|               0|                               5941|                  1729|
|     168|         0|operational_start |1994-05-15 | 21.000000| 100| 3.960000|     8.65|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-05-15             |                            0|                      0|            0|                 0|                 0|               0|                                 -7|                    -7|
|     168|         1|pump_test_2       |1994-05-08 | 24.390245| 100| 4.350000|       NA|      8.45| 1.1614402|FALSE      |TRUE            |FALSE           |FALSE         |1994-05-15             |                           -7|                     -7|            0|                 1|                 0|               0|                                 -7|                    -7|
|     168|         2|pump_test_1       |2000-06-25 | 20.484170| 110| 7.900000|       NA|     13.27| 0.9754367|NA         |NA              |NA              |NA            |1994-05-15             |                         2233|                   2240|            0|                 1|                 0|               0|                                 -7|                    -7|
|     168|         2|pump_test_2       |2000-07-16 | 21.929825| 100| 6.480000|       NA|     11.04| 1.0442774|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-15             |                         2254|                     21|            1|                 2|                 0|               0|                               2254|                  2261|
|     168|         3|pump_test_1       |2005-12-04 | 16.077170|  50| 5.570000|       NA|      8.68| 0.7655795|NA         |NA              |NA              |NA            |1994-05-15             |                         4221|                   1967|            1|                 2|                 0|               0|                               2254|                  2261|
|     168|         3|pump_test_2       |2005-12-18 | 16.556292|  50| 4.290000|       NA|      7.31| 0.7883948|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-15             |                         4235|                     14|            2|                 3|                 0|               0|                               4235|                  1981|
|     168|         4|pump_test_1       |2010-04-19 |  8.000000|  50| 8.670000|       NA|     14.92| 0.3809524|NA         |NA              |NA              |NA            |1994-05-15             |                         5818|                   1583|            2|                 3|                 0|               0|                               4235|                  1981|
|     168|         4|pump_test_2       |2010-05-04 | 13.850417|  50| 5.760000|       NA|      9.37| 0.6595437|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-15             |                         5833|                     15|            3|                 4|                 0|               0|                               5833|                  1598|
|     168|         5|pump_test_1       |2015-03-23 |  5.718954|  35| 7.660000|       NA|     13.78| 0.2723312|NA         |NA              |NA              |NA            |1994-05-15             |                         7617|                   1784|            3|                 4|                 0|               0|                               5833|                  1598|
|     168|         5|pump_test_2       |2015-03-30 |  9.633911|  50| 7.200000|       NA|     12.39| 0.4587577|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-15             |                         7624|                      7|            4|                 5|                 0|               0|                               7624|                  1791|
|     169|         0|operational_start |1994-05-08 | 29.000000| 120| 4.900000|     9.11|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-05-08             |                            0|                      0|            0|                 0|                 0|               0|                                 -5|                    -5|
|     169|         1|pump_test_2       |1994-05-03 | 24.024025|  80| 2.850000|       NA|      6.18| 0.8284146|FALSE      |TRUE            |FALSE           |FALSE         |1994-05-08             |                           -5|                     -5|            0|                 1|                 0|               0|                                 -5|                    -5|
|     169|         2|pump_test_2       |1999-10-12 | 27.586202|  88| 8.950000|       NA|     12.14| 0.9512484|FALSE      |TRUE            |FALSE           |FALSE         |1994-05-08             |                         1983|                   1988|            0|                 2|                 0|               0|                                 -5|                    -5|
|     169|         3|pump_test_1       |1999-10-12 | 27.586202|  88| 8.950000|       NA|     12.14| 0.9512484|NA         |NA              |NA              |NA            |1994-05-08             |                         1983|                      0|            0|                 2|                 0|               0|                                 -5|                    -5|
|     169|         3|pump_test_2       |2000-05-03 | 21.176473| 108| 6.630000|       NA|     11.73| 0.7302232|TRUE       |FALSE           |FALSE           |FALSE         |1994-05-08             |                         2187|                    204|            1|                 2|                 0|               0|                               2187|                  2192|
|     169|         4|pump_test_2       |2000-05-28 | 24.343672| 102| 8.650000|       NA|     12.84| 0.8394370|FALSE      |TRUE            |FALSE           |FALSE         |1994-05-08             |                         2212|                     25|            1|                 3|                 0|               0|                               2187|                  2192|
|     169|         5|pump_test_1       |2005-12-11 | 18.306639|  80| 4.820000|       NA|      9.19| 0.6312634|NA         |NA              |NA              |NA            |1994-05-08             |                         4235|                   2023|            1|                 3|                 0|               0|                               2187|                  2192|
|     169|         5|pump_test_2       |2005-12-15 | 18.735363|  80| 4.480000|       NA|      8.75| 0.6460470|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-08             |                         4239|                      4|            2|                 4|                 0|               0|                               4239|                  2052|
|     169|         6|pump_test_1       |2010-08-23 | 12.882447|  80| 5.810000|       NA|     12.02| 0.4442223|NA         |NA              |NA              |NA            |1994-05-08             |                         5951|                   1712|            2|                 4|                 0|               0|                               4239|                  2052|
|     169|         6|pump_test_2       |2010-10-20 | 15.999999|  80| 6.600000|       NA|     11.60| 0.5517241|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-08             |                         6009|                     58|            3|                 5|                 0|               0|                               6009|                  1770|
|     169|         7|pump_test_1       |2015-02-05 |  8.658009| 100| 6.800000|       NA|     18.35| 0.2985520|NA         |NA              |NA              |NA            |1994-05-08             |                         7578|                   1569|            3|                 5|                 0|               0|                               6009|                  1770|
|     169|         7|pump_test_2       |2015-03-15 | 12.326656|  80| 6.760000|       NA|     13.25| 0.4250571|TRUE       |TRUE            |TRUE            |FALSE         |1994-05-08             |                         7616|                     38|            4|                 6|                 1|               0|                               7616|                  1607|
|     170|         0|operational_start |1994-05-18 | 33.000000| 180| 5.320000|    10.70|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-05-18             |                            0|                      0|            0|                 0|                 0|               0|                                  0|                     0|
|     170|         1|pump_test_2       |1998-06-23 | 19.569471| 100| 7.150000|       NA|     12.26| 0.5930143|FALSE      |TRUE            |FALSE           |FALSE         |1994-05-18             |                         1497|                   1497|            0|                 1|                 0|               0|                                  0|                     0|
|     170|         2|pump_test_1       |2000-06-25 | 22.903884| 112| 8.240000|       NA|     13.13| 0.6940571|NA         |NA              |NA              |NA            |1994-05-18             |                         2230|                    733|            0|                 1|                 0|               0|                                  0|                     0|
|     170|         2|pump_test_2       |2000-07-16 | 22.573362| 100| 6.540000|       NA|     10.97| 0.6840413|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-18             |                         2251|                     21|            1|                 2|                 0|               0|                               2251|                  2251|
|     170|         3|pump_test_1       |2005-11-29 | 13.793103|  80| 6.250000|       NA|     12.05| 0.4179728|NA         |NA              |NA              |NA            |1994-05-18             |                         4213|                   1962|            1|                 2|                 0|               0|                               2251|                  2251|
|     170|         3|pump_test_2       |2005-12-08 | 19.512196|  80| 5.100000|       NA|      9.20| 0.5912787|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-18             |                         4222|                      9|            2|                 3|                 0|               0|                               4222|                  1971|
|     170|         4|pump_test_1       |2010-10-13 | 13.966480| 100| 7.850000|       NA|     15.01| 0.4232267|NA         |NA              |NA              |NA            |1994-05-18             |                         5992|                   1770|            2|                 3|                 0|               0|                               4222|                  1971|
|     170|         4|pump_test_2       |2010-12-01 | 14.184398| 100| 3.480000|       NA|     10.53| 0.4298302|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-18             |                         6041|                     49|            3|                 4|                 0|               0|                               6041|                  1819|
|     170|         5|pump_test_2       |2012-08-16 | 13.692946|  66| 7.600000|       NA|     12.42| 0.4149378|FALSE      |TRUE            |FALSE           |FALSE         |1994-05-18             |                         6665|                    624|            3|                 5|                 0|               0|                               6041|                  1819|
|     171|         0|operational_start |1994-05-02 | 28.000000| 180| 5.050000|    11.51|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-05-02             |                            0|                      0|            0|                 0|                 0|               0|                                  0|                     0|
|     171|         1|pump_test_1       |2000-04-02 | 22.813689| 120| 5.850000|       NA|     11.11| 0.8147746|NA         |NA              |NA              |NA            |1994-05-02             |                         2162|                   2162|            0|                 0|                 0|               0|                                  0|                     0|
|     171|         1|pump_test_2       |2000-08-20 | 24.489793| 120| 7.200000|       NA|     12.10| 0.8746355|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-02             |                         2302|                    140|            1|                 1|                 0|               0|                               2302|                  2302|
|     171|         2|pump_test_1       |2005-11-20 | 19.960079| 100| 7.580000|       NA|     12.59| 0.7128600|NA         |NA              |NA              |NA            |1994-05-02             |                         4220|                   1918|            1|                 1|                 0|               0|                               2302|                  2302|
|     171|         2|pump_test_2       |2005-11-28 | 20.120725| 100| 6.480000|       NA|     11.45| 0.7185973|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-02             |                         4228|                      8|            2|                 2|                 0|               0|                               4228|                  1926|
|     171|         3|pump_test_1       |2010-04-04 | 15.267175| 100| 8.229999|       NA|     14.78| 0.5452563|NA         |NA              |NA              |NA            |1994-05-02             |                         5816|                   1588|            2|                 2|                 0|               0|                               4228|                  1926|
|     171|         3|pump_test_2       |2010-04-20 | 21.929825| 100| 7.720000|       NA|     12.28| 0.7832080|TRUE       |TRUE            |FALSE           |FALSE         |1994-05-02             |                         5832|                     16|            3|                 3|                 0|               0|                               5832|                  1604|
|     171|         4|pump_test_1       |2015-06-17 | 14.962594|  60| 7.360000|       NA|     11.37| 0.5343783|NA         |NA              |NA              |NA            |1994-05-02             |                         7716|                   1884|            3|                 3|                 0|               0|                               5832|                  1604|
|     171|         4|pump_test_2       |2015-07-01 | 15.590200|  70| 7.030000|       NA|     11.52| 0.5567929|TRUE       |TRUE            |TRUE            |FALSE         |1994-05-02             |                         7730|                     14|            4|                 4|                 1|               0|                               7730|                  1898|
|     172|         0|operational_start |1971-02-11 | 20.000000| 150| 7.700000|    15.05|        NA| 1.0000000|NA         |NA              |NA              |NA            |1971-02-11             |                            0|                      0|            0|                 0|                 0|               0|                                  0|                     0|
|     172|         1|pump_test_2       |1993-08-31 | 18.115941| 100| 5.580000|       NA|     11.10| 0.9057970|TRUE       |FALSE           |FALSE           |FALSE         |1971-02-11             |                         8237|                   8237|            1|                 0|                 0|               0|                               8237|                  8237|
|     172|         2|pump_test_1       |2000-07-11 | 12.096774| 105| 9.000000|       NA|     17.68| 0.6048387|NA         |NA              |NA              |NA            |1971-02-11             |                        10743|                   2506|            1|                 0|                 0|               0|                               8237|                  8237|
|     172|         2|pump_test_2       |2000-08-27 | 17.073171|  70| 6.820000|       NA|     10.92| 0.8536586|TRUE       |TRUE            |FALSE           |FALSE         |1971-02-11             |                        10790|                     47|            2|                 1|                 0|               0|                              10790|                  2553|
|     172|         3|pump_test_1       |2005-10-03 |  8.488964|  50| 7.270000|       NA|     13.16| 0.4244482|NA         |NA              |NA              |NA            |1971-02-11             |                        12653|                   1863|            2|                 1|                 0|               0|                              10790|                  2553|
|     172|         3|pump_test_2       |2005-10-20 |  9.900990|  50| 6.540000|       NA|     11.59| 0.4950495|TRUE       |TRUE            |FALSE           |FALSE         |1971-02-11             |                        12670|                     17|            3|                 2|                 0|               0|                              12670|                  1880|
|     173|         0|operational_start |1994-04-10 | 14.000000| 120| 4.880000|    13.31|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-04-10             |                            0|                      0|            0|                 0|                 0|               0|                                 -5|                    -5|
|     173|         1|pump_test_2       |1994-04-05 | 16.835015| 100| 3.620000|       NA|      9.56| 1.2025011|FALSE      |TRUE            |FALSE           |FALSE         |1994-04-10             |                           -5|                     -5|            0|                 1|                 0|               0|                                 -5|                    -5|
|     173|         2|pump_test_1       |2000-07-13 | 14.603961| 118| 7.610000|       NA|     15.69| 1.0431401|NA         |NA              |NA              |NA            |1994-04-10             |                         2286|                   2291|            0|                 1|                 0|               0|                                 -5|                    -5|
|     173|         2|pump_test_2       |2000-08-10 | 14.669928|  60| 6.100000|       NA|     10.19| 1.0478520|TRUE       |TRUE            |FALSE           |FALSE         |1994-04-10             |                         2314|                     28|            1|                 2|                 0|               0|                               2314|                  2319|
|     173|         3|pump_test_1       |2005-10-24 |  9.677419|  60| 5.270000|       NA|     11.47| 0.6912442|NA         |NA              |NA              |NA            |1994-04-10             |                         4215|                   1901|            1|                 2|                 0|               0|                               2314|                  2319|
|     173|         3|pump_test_2       |2005-11-24 | 10.600708|  60| 5.320000|       NA|     10.98| 0.7571934|TRUE       |TRUE            |FALSE           |FALSE         |1994-04-10             |                         4246|                     31|            2|                 3|                 0|               0|                               4246|                  1932|
|     173|         4|pump_test_1       |2010-08-24 |  8.313539|  70| 5.580000|       NA|     14.00| 0.5938242|NA         |NA              |NA              |NA            |1994-04-10             |                         5980|                   1734|            2|                 3|                 0|               0|                               4246|                  1932|
|     173|         4|pump_test_2       |2010-09-12 | 11.844331|  70| 4.730000|       NA|     10.64| 0.8460236|TRUE       |TRUE            |FALSE           |FALSE         |1994-04-10             |                         5999|                     19|            3|                 4|                 0|               0|                               5999|                  1753|
|     173|         5|pump_test_1       |2015-01-28 |  7.342144| 100| 7.300000|       NA|     20.92| 0.5244389|NA         |NA              |NA              |NA            |1994-04-10             |                         7598|                   1599|            3|                 4|                 0|               0|                               5999|                  1753|
|     173|         5|pump_test_2       |2015-03-03 |  9.124088|  50| 5.950000|       NA|     11.43| 0.6517205|TRUE       |TRUE            |TRUE            |FALSE         |1994-04-10             |                         7632|                     34|            4|                 5|                 1|               0|                               7632|                  1633|
|     174|         0|operational_start |1971-02-11 | 40.000000| 150| 4.800000|     8.51|        NA| 1.0000000|NA         |NA              |NA              |NA            |1971-02-11             |                            0|                      0|            0|                 0|                 0|               0|                                  0|                     0|
|     174|         1|pump_test_2       |1993-08-15 | 37.500005| 150| 5.400000|       NA|      9.40| 0.9375001|TRUE       |FALSE           |FALSE           |FALSE         |1971-02-11             |                         8221|                   8221|            1|                 0|                 0|               0|                               8221|                  8221|
|     174|         2|pump_test_1       |2000-07-23 | 34.730541| 174| 6.640000|       NA|     11.65| 0.8682635|NA         |NA              |NA              |NA            |1971-02-11             |                        10755|                   2534|            1|                 0|                 0|               0|                               8221|                  8221|
|     174|         2|pump_test_2       |2000-08-07 | 38.314174| 100| 6.600000|       NA|      9.21| 0.9578544|TRUE       |TRUE            |FALSE           |FALSE         |1971-02-11             |                        10770|                     15|            2|                 1|                 0|               0|                              10770|                  2549|
|     174|         3|pump_test_1       |2005-11-20 | 28.169013| 120| 5.200000|       NA|      9.46| 0.7042253|NA         |NA              |NA              |NA            |1971-02-11             |                        12701|                   1931|            2|                 1|                 0|               0|                              10770|                  2549|
|     174|         3|pump_test_2       |2005-12-06 | 30.150754| 120| 4.900000|       NA|      8.88| 0.7537688|TRUE       |TRUE            |FALSE           |FALSE         |1971-02-11             |                        12717|                     16|            3|                 2|                 0|               0|                              12717|                  1947|
|     174|         4|pump_test_2       |2008-06-08 | 29.339852| 120| 7.200000|       NA|     11.29| 0.7334963|FALSE      |FALSE           |FALSE           |TRUE          |1971-02-11             |                        13632|                    915|            3|                 2|                 0|               1|                              12717|                  1947|
|     174|         5|pump_test_1       |2015-09-16 | 33.444816| 100| 7.210000|       NA|     10.20| 0.8361204|NA         |NA              |NA              |NA            |1971-02-11             |                        16288|                   2656|            3|                 2|                 0|               1|                              12717|                  1947|
|     174|         5|pump_test_2       |2015-09-28 | 30.395137| 100| 5.420000|       NA|      8.71| 0.7598784|TRUE       |TRUE            |FALSE           |FALSE         |1971-02-11             |                        16300|                     12|            4|                 3|                 0|               1|                              16300|                  3583|
|     177|         0|operational_start |1970-09-22 | 22.000000| 150| 6.380000|    13.05|        NA| 1.0000000|NA         |NA              |NA              |NA            |1970-09-22             |                            0|                      0|            0|                 0|                 0|               0|                                  0|                     0|
|     177|         1|pump_test_2       |1994-03-07 | 18.181818| 100| 8.650000|       NA|     14.15| 0.8264463|TRUE       |FALSE           |FALSE           |FALSE         |1970-09-22             |                         8567|                   8567|            1|                 0|                 0|               0|                               8567|                  8567|
|     177|         2|pump_test_1       |2000-08-29 |  7.878788|  65| 6.610000|       NA|     14.86| 0.3581267|NA         |NA              |NA              |NA            |1970-09-22             |                        10934|                   2367|            1|                 0|                 0|               0|                               8567|                  8567|
|     177|         2|pump_test_2       |2000-10-09 | 10.093168|  65| 5.880000|       NA|     12.32| 0.4587804|TRUE       |TRUE            |FALSE           |FALSE         |1970-09-22             |                        10975|                     41|            2|                 1|                 0|               0|                              10975|                  2408|
|     177|         3|pump_test_1       |2005-09-06 |  7.363770|  50| 7.660000|       NA|     14.45| 0.3347168|NA         |NA              |NA              |NA            |1970-09-22             |                        12768|                   1793|            2|                 1|                 0|               0|                              10975|                  2408|
|     177|         3|pump_test_2       |2005-09-20 |  7.886436|  50| 7.890000|       NA|     14.23| 0.3584744|TRUE       |TRUE            |FALSE           |FALSE         |1970-09-22             |                        12782|                     14|            3|                 2|                 0|               0|                              12782|                  1807|
