### ISSUE TITLE
generate artificial "action_date" and fix "days_since_last_rehab"

### ISSUE THREAD

**Issue by mrustl** [KWB-R/dwc.wells#16]
- [x] calculate mean time difference between first / second pump test (average over all wells)
- [x] fill date.pump_test_1 and date.pump_test_2 if NA with +/- time difference 
- [x] fill "action_date" 
- [x] fix **days_since_last_rehab**

**Comment by mriech** [comment]
screenshot, as discussed.
![screenshot_pump_test_data_v2](https://user-images.githubusercontent.com/47454653/118667656-7b17e980-b7f4-11eb-97cd-e4d62611aa72.PNG)

**Comment by mrustl** [comment]
Fixes as listed above plus the following modifications:

-  Removed column **days_since_last_actions**
-  Created **intervall_days** and **intervall_type** (real -> if no data gaps, **default**: in case of data gaps, backcalculated from wells "global mean")

| well_id| action_id|action_date |intervall_days |intervall_type |key               |date       |        Qs|   Q| W_static| W_dyamic| W_dynamic|    Qs_rel|well_rehab |substitute_pump |pressure_sleeve |comment_liner |operational_start.date | days_since_operational_start| days_since_last_action| n.well_rehab| n.substitute_pump| n.pressure_sleeve| n.comment_liner| days_since_last_rehab|
|-------:|---------:|:-----------|:--------------|:--------------|:-----------------|:----------|---------:|---:|--------:|--------:|---------:|---------:|:----------|:---------------|:---------------|:-------------|:----------------------|----------------------------:|----------------------:|------------:|-----------------:|-----------------:|---------------:|---------------------:|
|     162|         0|1970-12-14  |28             |default        |operational_start |1970-12-14 | 39.000000| 150|     5.60|     9.44|        NA| 1.0000000|NA         |NA              |NA              |NA            |1970-12-14             |                            0|                      0|            0|                 0|                 0|               0|                    NA|
|     162|         1|1994-01-30  |28             |default        |pump_test_1       |1994-01-16 |        NA|  NA|       NA|       NA|        NA|        NA|NA         |NA              |NA              |NA            |1970-12-14             |                         8434|                   8434|            0|                 0|                 0|               0|                    NA|
|     162|         1|1994-01-30  |28             |default        |pump_test_2       |1994-02-13 | 38.216556| 180|     4.72|       NA|      9.43| 0.9799117|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                         8462|                     28|            1|                 1|                 0|               0|                    14|
|     162|         2|2000-05-09  |59             |real           |pump_test_1       |2000-04-09 | 29.329608| 210|     5.18|       NA|     12.34| 0.7520412|NA         |NA              |NA              |NA            |1970-12-14             |                        10709|                   2247|            1|                 1|                 0|               0|                  2261|
|     162|         2|2000-05-09  |59             |real           |pump_test_2       |2000-06-07 | 30.648332| 156|     6.03|       NA|     11.12| 0.7858547|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                        10768|                     59|            2|                 2|                 0|               0|                    29|
|     162|         3|2005-11-29  |3              |real           |pump_test_1       |2005-11-27 | 20.408165|  50|     4.84|       NA|      7.29| 0.5232863|NA         |NA              |NA              |NA            |1970-12-14             |                        12767|                   1999|            2|                 2|                 0|               0|                  2028|
|     162|         3|2005-11-29  |3              |real           |pump_test_2       |2005-11-30 | 23.923449|  50|     4.84|       NA|      6.93| 0.6134218|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                        12770|                      3|            3|                 3|                 0|               0|                     1|
|     162|         4|2010-07-07  |15             |real           |pump_test_1       |2010-06-29 | 15.444016| 120|     5.22|       NA|     12.99| 0.3960004|NA         |NA              |NA              |NA            |1970-12-14             |                        14442|                   1672|            3|                 3|                 0|               0|                  1673|
|     162|         4|2010-07-07  |15             |real           |pump_test_2       |2010-07-14 | 19.512195| 120|     6.18|       NA|     12.33| 0.5003127|TRUE       |TRUE            |TRUE            |FALSE         |1970-12-14             |                        14457|                     15|            4|                 4|                 1|               0|                     7|
|     162|         5|2013-07-21  |245            |real           |pump_test_1       |2013-03-20 | 12.307692|  40|     5.60|       NA|      8.85| 0.3155819|NA         |NA              |NA              |NA            |1970-12-14             |                        15437|                    980|            4|                 4|                 1|               0|                   987|
|     162|         5|2013-07-21  |245            |real           |pump_test_2       |2013-11-20 | 10.638298|  50|     6.38|       NA|     11.08| 0.2727769|TRUE       |TRUE            |FALSE           |TRUE          |1970-12-14             |                        15682|                    245|            5|                 5|                 1|               1|                   122|
|     162|         6|2015-03-02  |28             |default        |pump_test_1       |2015-02-16 |  8.103728|  50|     6.45|       NA|     12.62| 0.2077879|NA         |NA              |NA              |NA            |1970-12-14             |                        16135|                    453|            5|                 5|                 1|               1|                   575|
|     162|         6|2015-03-02  |28             |default        |pump_test_2       |2015-03-16 |        NA|  NA|       NA|       NA|        NA|        NA|FALSE      |FALSE           |FALSE           |FALSE         |1970-12-14             |                        16163|                     28|            5|                 5|                 1|               1|                   603|
|     166|         1|1994-05-09  |28             |default        |pump_test_1       |1994-04-25 |        NA|  NA|       NA|       NA|        NA|        NA|NA         |NA              |NA              |NA            |1994-06-01             |                          -37|                    -37|            0|                 0|                 0|               0|                    NA|
|     166|         1|1994-05-09  |28             |default        |pump_test_2       |1994-05-23 | 48.387098| 150|     5.40|       NA|      8.50| 1.0752689|FALSE      |TRUE            |FALSE           |FALSE         |1994-06-01             |                           -9|                     28|            0|                 1|                 0|               0|                    NA|
|     166|         0|1994-06-01  |28             |default        |operational_start |1994-06-01 | 45.000000| 180|     3.81|     7.84|        NA| 1.0000000|NA         |NA              |NA              |NA            |1994-06-01             |                            0|                      0|            0|                 0|                 0|               0|                    NA|
|     166|         2|2000-06-16  |23             |real           |pump_test_1       |2000-06-04 | 53.571426| 180|     7.06|       NA|     10.42| 1.1904761|NA         |NA              |NA              |NA            |1994-06-01             |                         2195|                   2204|            0|                 1|                 0|               0|                    NA|
|     166|         2|2000-06-16  |23             |real           |pump_test_2       |2000-06-27 | 41.131102| 160|     8.13|       NA|     12.02| 0.9140245|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         2218|                     23|            1|                 2|                 0|               0|                    11|
|     166|         3|2005-12-16  |8              |real           |pump_test_1       |2005-12-12 | 31.152652| 100|     4.53|       NA|      7.74| 0.6922812|NA         |NA              |NA              |NA            |1994-06-01             |                         4212|                   1994|            1|                 2|                 0|               0|                  2005|
|     166|         3|2005-12-16  |8              |real           |pump_test_2       |2005-12-20 | 32.573288| 100|     4.18|       NA|      7.25| 0.7238508|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         4220|                      8|            2|                 3|                 0|               0|                     4|
