### ISSUE TITLE
Aggregate abstraction volume data

### ISSUE THREAD

**Issue by mriech** [KWB-R/dwc.wells#20]
Hi @mrustl, as discussed on the phone...

there are two data frames: 

- the model data that consist of the relative Qs-values and the well features ("model_data.RData") and
- time series data of the abstraction volume of the different wells ("volume_data.RData"). 

You'll find the two data frames in ```\inst\extdata\data_out```.

Could you please calculate the total volume abstracted for each well between each date of Qs-measurements and the respective date of the last rehab? In the model data you find the columns 'date' and "last_rehab.date" which you can use as limits for aggregating the abstraction volumes for the corresponding well. 

You can open a new script in ```\inst\extdata\data_out``` and I will then integrate it in the workflow.

Let me know if you have any questions.

Best,
Matze

**Comment by mrustl** [comment]
Thanks! Just before starting: your R analysis showed that we currently will loose a lot of data points (I would guess more than 40%)  in case we take `abstraction` data into account. So do we still want to start now (for many wells, would guess > 50% we are lacking the `abstraction volume` after installation) or wait for BWB feedback if more data is available?

**Comment by mriech** [comment]
Yes, good point. I would say, it would be good to test that already now. If the abstraction volume is one of the main drivers of well ageing it might be worth discarding half of the data points while including that variable in the model. And we could eventually demonstrate to BWB the importance of those data.

**Comment by mrustl** [comment]
Hi @mrustl, thanks. However, I think at the moment, data is only aggregated between the different rehab.dates but not between date and rehab.date, isn't it?

For well_id 162, as an example, we would need for each

- [ ]  row the volume abstracted between date and last_rehab.date and
- [ ]  eventually also between date_and operational_start.date, as an extra). If volume data is incomplete for a time interval, there should be an NA.

well_id | date | last_rehab.date | operational_start.date | key | Qs_rel
-- | -- | -- | -- | -- | --
162 | 1970-12-15 | 1970-12-15 | 1970-12-15 | operational_start | 1.000
162 | 1994-02-14 | 1994-01-30 | 1970-12-15 | pump_test_2 | 0.978
162 | 2000-04-10 | 1994-01-30 | 1970-12-15 | pump_test_1 | 0.751
162 | 2000-06-08 | 2000-05-10 | 1970-12-15 | pump_test_2 | 0.785
162 | 2005-11-28 | 2000-05-10 | 1970-12-15 | pump_test_1 | 0.522
162 | 2005-12-01 | 2005-11-30 | 1970-12-15 | pump_test_2 | 0.612
162 | 2013-03-21 | 2005-11-30 | 1970-12-15 | pump_test_1 | 0.315
162 | 2013-11-21 | 2013-07-22 | 1970-12-15 | pump_test_2 | 0.272
162 | 2015-02-17 | 2013-07-22 | 1970-12-15 | pump_test_1 | 0.207
162 | 2018-10-29 | 2013-07-22 | 1970-12-15 | pump_test_1 | 0.163
162 | 2018-11-12 | 2018-11-05 | 1970-12-15 | pump_test_2 | 0.224

What do you think?
