### ISSUE TITLE
feat: prepare "tidy" wells feature table

### ISSUE THREAD

**Issue by mrustl** [KWB-R/dwc.wells#5]
As proposed by @mriech 

![grafik](https://user-images.githubusercontent.com/11964451/116848741-890f1d00-abed-11eb-8122-87bd1e3ad749.png)

**Comment by mrustl** [comment]
Start with converting remaining German column names to English: 
```
str(df_pump_tests)
'data.frame':	3944 obs. of  16 variables:
 $ well_id               : int  162 162 162 162 162 162 162 166 166 166 ...
 $ operational_start.date: POSIXct, format: "1970-12-15" "1970-12-15" "1970-12-15" "1970-12-15" ...
 $ operational_start.Qs  : num  39 39 39 39 39 39 39 45 45 45 ...
 $ pump_test_1.date      : Date, format: NA "2000-04-09" "2005-11-27" "2010-06-29" ...
 $ pump_test_1.W_static  : num  NA 5.18 4.84 5.22 5.6 ...
 $ pump_test_1.W_dynamic : num  NA 12.34 7.29 12.99 8.85 ...
 $ pump_test_1.Q         : num  NA 210 50 120 40 50 NA NA 180 100 ...
 $ pump_test_2.date      : Date, format: "1994-02-13" "2000-06-07" "2005-11-30" "2010-07-14" ...
 $ pump_test_2.W_static  : num  4.72 6.03 4.84 6.18 6.38 ...
 $ pump_test_2.W_dynamic : num  9.43 11.12 6.93 12.33 11.08 ...
 $ pump_test_2.Q         : num  180 156 50 120 50 NA NA 150 160 100 ...
 $ pump_test_1.Qs        : num  NA 29.3 20.4 15.4 12.3 ...
 $ pump_test_2.Qs        : num  38.2 30.6 23.9 19.5 10.6 ...
 $ well_rehab            : logi  TRUE TRUE TRUE TRUE TRUE FALSE ...
 $ substitute_pump       : logi  TRUE TRUE TRUE TRUE TRUE FALSE ...
 $ pressure_sleeve       : logi  FALSE FALSE FALSE TRUE FALSE FALSE ..
```.

**Comment by mrustl** [comment]
Current status: 
- [x]  convert to wide format (see example below)
- [ ]  cumsum for "TRUE" actions (last columns)

| well_id| action_id|key               |date       |        Qs| W_static| W_dynamic|   Q|    Qs_rel|well_rehab |substitute_pump |pressure_sleeve |comment_liner |
|-------:|---------:|:-----------------|:----------|---------:|--------:|---------:|---:|---------:|:----------|:---------------|:---------------|:-------------|
|     162|         0|operational_start |1970-12-15 | 39.000000|       NA|        NA|  NA|        NA|NA         |NA              |NA              |NA            |
|     162|         1|pump_test_2       |1994-02-13 | 38.216556|     4.72|      9.43| 180| 0.9799117|TRUE       |TRUE            |FALSE           |FALSE         |
|     162|         2|pump_test_1       |2000-04-09 | 29.329608|     5.18|     12.34| 210| 0.7520412|NA         |NA              |NA              |NA            |
|     162|         2|pump_test_2       |2000-06-07 | 30.648332|     6.03|     11.12| 156| 0.7858547|TRUE       |TRUE            |FALSE           |FALSE         |
|     162|         3|pump_test_1       |2005-11-27 | 20.408165|     4.84|      7.29|  50| 0.5232863|NA         |NA              |NA              |NA            |
|     162|         3|pump_test_2       |2005-11-30 | 23.923449|     4.84|      6.93|  50| 0.6134218|TRUE       |TRUE            |FALSE           |FALSE         |
|     162|         4|pump_test_1       |2010-06-29 | 15.444016|     5.22|     12.99| 120| 0.3960004|NA         |NA              |NA              |NA            |
|     162|         4|pump_test_2       |2010-07-14 | 19.512195|     6.18|     12.33| 120| 0.5003127|TRUE       |TRUE            |TRUE            |FALSE         |
|     162|         5|pump_test_1       |2013-03-20 | 12.307692|     5.60|      8.85|  40| 0.3155819|NA         |NA              |NA              |NA            |
|     162|         5|pump_test_2       |2013-11-20 | 10.638298|     6.38|     11.08|  50| 0.2727769|TRUE       |TRUE            |FALSE           |TRUE          |
|     162|         6|pump_test_1       |2015-02-16 |  8.103728|     6.45|     12.62|  50| 0.2077879|NA         |NA              |NA              |NA            |
|     162|         6|pump_test_2       |NA         |        NA|       NA|        NA|  NA|        NA|FALSE      |FALSE           |FALSE           |FALSE         |
|     166|         0|operational_start |1994-06-02 | 45.000000|       NA|        NA|  NA|        NA|NA         |NA              |NA              |NA            |
|     166|         1|pump_test_2       |1994-05-23 | 48.387098|     5.40|      8.50| 150| 1.0752689|FALSE      |TRUE            |FALSE           |FALSE         |
|     166|         2|pump_test_1       |2000-06-04 | 53.571426|     7.06|     10.42| 180| 1.1904761|NA         |NA              |NA              |NA            |
|     166|         2|pump_test_2       |2000-06-27 | 41.131102|     8.13|     12.02| 160| 0.9140245|TRUE       |TRUE            |FALSE           |FALSE         |
|     166|         3|pump_test_1       |2005-12-12 | 31.152652|     4.53|      7.74| 100| 0.6922812|NA         |NA              |NA              |NA            |
|     166|         3|pump_test_2       |2005-12-20 | 32.573288|     4.18|      7.25| 100| 0.7238508|TRUE       |TRUE            |FALSE           |FALSE         |
|     166|         4|pump_test_1       |2010-05-02 | 18.484287|     6.31|     11.72| 100| 0.4107619|NA         |NA              |NA              |NA            |
|     166|         4|pump_test_2       |2010-05-19 | 32.258066|     5.18|      8.28| 100| 0.7168459|TRUE       |TRUE            |FALSE           |FALSE         |
|     166|         5|pump_test_1       |2015-04-21 | 15.682657|     7.49|     12.91|  85| 0.3485035|NA         |NA              |NA              |NA            |
|     166|         5|pump_test_2       |2015-05-11 | 23.460411|     6.09|      9.50|  80| 0.5213425|TRUE       |TRUE            |FALSE           |FALSE         |

**Comment by mriech** [comment]
Look great, Michael. This helps a lot! Thanks!

I have notes a few questions for our meeting this afternoon. I would also like to merge our two branches to dev with you together. See you.

**Comment by mrustl** [comment]
Current status (#11)
- [x]  convert to wide format (see example below)
- [x]  cumsum for "TRUE" actions (last columns)
- [x] Add more dates (operational_start.date, days_since_operational_start, days_since_last_action)
- [x]  100% Qs for operational start
- [ ]  ????

| well_id| action_id|key               |date       |        Qs|   Q| W_static| W_dyamic| W_dynamic|      Qs_rel|well_rehab |substitute_pump |pressure_sleeve |comment_liner |operational_start.date | days_since_operational_start| days_since_last_action| n.well_rehab| n.substitute_pump| n.pressure_sleeve| n.comment_liner|
|-------:|---------:|:-----------------|:----------|---------:|---:|--------:|--------:|---------:|-----------:|:----------|:---------------|:---------------|:-------------|:----------------------|----------------------------:|----------------------:|------------:|-----------------:|-----------------:|---------------:|
|     162|         0|operational_start |1970-12-14 | 39.000000| 150|     5.60|     9.44|        NA| 100.0000000|NA         |NA              |NA              |NA            |1970-12-14             |                            0|                      0|            0|                 0|                 0|               0|
|     162|         1|pump_test_2       |1994-02-13 | 38.216556| 180|     4.72|       NA|      9.43|   0.9799117|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                         8462|                   8462|            1|                 1|                 0|               0|
|     162|         2|pump_test_1       |2000-04-09 | 29.329608| 210|     5.18|       NA|     12.34|   0.7520412|NA         |NA              |NA              |NA            |1970-12-14             |                        10709|                   2247|            1|                 1|                 0|               0|
|     162|         2|pump_test_2       |2000-06-07 | 30.648332| 156|     6.03|       NA|     11.12|   0.7858547|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                        10768|                     59|            2|                 2|                 0|               0|
|     162|         3|pump_test_1       |2005-11-27 | 20.408165|  50|     4.84|       NA|      7.29|   0.5232863|NA         |NA              |NA              |NA            |1970-12-14             |                        12767|                   1999|            2|                 2|                 0|               0|
|     162|         3|pump_test_2       |2005-11-30 | 23.923449|  50|     4.84|       NA|      6.93|   0.6134218|TRUE       |TRUE            |FALSE           |FALSE         |1970-12-14             |                        12770|                      3|            3|                 3|                 0|               0|
|     162|         4|pump_test_1       |2010-06-29 | 15.444016| 120|     5.22|       NA|     12.99|   0.3960004|NA         |NA              |NA              |NA            |1970-12-14             |                        14442|                   1672|            3|                 3|                 0|               0|
|     162|         4|pump_test_2       |2010-07-14 | 19.512195| 120|     6.18|       NA|     12.33|   0.5003127|TRUE       |TRUE            |TRUE            |FALSE         |1970-12-14             |                        14457|                     15|            4|                 4|                 1|               0|
|     162|         5|pump_test_1       |2013-03-20 | 12.307692|  40|     5.60|       NA|      8.85|   0.3155819|NA         |NA              |NA              |NA            |1970-12-14             |                        15437|                    980|            4|                 4|                 1|               0|
|     162|         5|pump_test_2       |2013-11-20 | 10.638298|  50|     6.38|       NA|     11.08|   0.2727769|TRUE       |TRUE            |FALSE           |TRUE          |1970-12-14             |                        15682|                    245|            5|                 5|                 1|               1|
|     162|         6|pump_test_1       |2015-02-16 |  8.103728|  50|     6.45|       NA|     12.62|   0.2077879|NA         |NA              |NA              |NA            |1970-12-14             |                        16135|                    453|            5|                 5|                 1|               1|
|     162|         6|pump_test_2       |NA         |        NA|  NA|       NA|       NA|        NA|          NA|FALSE      |FALSE           |FALSE           |FALSE         |1970-12-14             |                           NA|                     NA|            5|                 5|                 1|               1|
|     166|         0|operational_start |1994-06-01 | 45.000000| 180|     3.81|     7.84|        NA| 100.0000000|NA         |NA              |NA              |NA            |1994-06-01             |                            0|                      0|            0|                 0|                 0|               0|
|     166|         1|pump_test_2       |1994-05-23 | 48.387098| 150|     5.40|       NA|      8.50|   1.0752689|FALSE      |TRUE            |FALSE           |FALSE         |1994-06-01             |                           -9|                     -9|            0|                 1|                 0|               0|
|     166|         2|pump_test_1       |2000-06-04 | 53.571426| 180|     7.06|       NA|     10.42|   1.1904761|NA         |NA              |NA              |NA            |1994-06-01             |                         2195|                   2204|            0|                 1|                 0|               0|
|     166|         2|pump_test_2       |2000-06-27 | 41.131102| 160|     8.13|       NA|     12.02|   0.9140245|TRUE       |TRUE            |FALSE           |FALSE         |1994-06-01             |                         2218|                     23|            1|                 2|                 0|               0|
